Network:
  batch_size: 124
  lr: 4e-5
  weight_decay: 0
  amsgrad: False
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth


# changeable items:
file_path: /home/soroosh/Documents/datasets/Histopathology/soroosh_based/
target_dir: /home/soroosh/Documents/Repositories_target_files/federated_he/pathology/
network_save_freq: 1 # shows the number of epochs done
display_stats_freq: 1 # valid freq is equal to this [MUST be 1 for this project]
num_epochs: 60